#!/usr/bin/tcsh
while 1
  while 1
    echo -n "\nEnter your choice: "
    set ch = $<
    if ( $ch =~ [a-h][1-6] ) break
    echo "Invalid choice. Please try again."
  end
  set x = `echo $ch | sed 'y/abcdefgh/12345678/;s/\([1-8]\)\([1-8]\)/8 \* \2 + \1 + -8/g' | xargs expr`
  ( expr $x:q != $1:q && expr 1 `cat memboard | sed -n "$x s/_/&/p"` ) >& /dev/null && exit $x
  echo "That place is already revealed. Please try again."
end

#echo $ch | grep -o . | grep -n '[a-h]' | grep "1:" >& /dev/null && echo $ch | grep -o . | grep -n '[1-6]' | grep "2:" >& /dev/null && break