#!/usr/bin/tcsh
echo -n ABCDEFGHIJKLMNOPQRSTUVWX | sed 's/./&\n/g' | tr -d 1 | tee memboard | tr A-Z a-z > lets; cat memboard >> lets
set arraylets = ( `cat lets` )
set arraysymbols = ( `sed -n 's/./&/p' symbols | sort -R | sed -n '1,24 p'` )
echo -n "#\!/bin/sed -f\ny/$arraylets/$arraysymbols $arraysymbols/" > sedfile
cat lets | sort -R | tr "a-z" "A-Z" > memboard
@ choice1 = 50
@ choice2 = 50
@ cnt = 0
while (1)
  ./displayboard $choice1 $choice2 X$1
  if ($? == 1) then
    expr 1 `cat f3 | sed -n 's/[A-Za-z\?]/0/p'` >&/dev/null && echo \\nCongratulations\! Finished in $cnt moves.\\n && exit
    mv -f f3 memboard
  endif
  ./getchoice 50
  set choice1 = $?
  ./displayboard $choice1 50 X$1
  ./getchoice $choice1
  set choice2 = $?
  @ cnt++
end
