#!/usr/bin/tcsh
clear
if( "$3" == "-c" )	then
	echo "   a  b  c  d  e  f  g  h\n"
	grep -o ' [A-X], [A-X], [A-X], [A-X], [A-X], [A-X], [A-X], [A-X],' memboard | grep -n '.' | tr ':,' '  ' > tmp
	seq 10 10 50 >> tmp
	sort tmp | grep -C0  '[0-6]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X] ' | __2__
	echo "\n-------------------------\n"
endif
cat memboard | tr ',' '\n' | cat -n > file
grep -e '^'$1'\t' -e '^'$2'\t' file > tmp

grep -v $2 file | tr '[A-X]' '?' >> tmp
sort tmp | tr __2__ | tr '\n\t' ', ' > tmp2
echo "   a  b  c  d  e  f  g  h\n"
grep -o ' [A-X], [A-X], [A-X], [A-X], [A-X], [A-X], [A-X], [A-X],' memboard | grep -n '.' | tr ':,' '  ' > tmp
seq 10 10 50 >> tmp
sort tmp | grep -C0 -w '[0-6]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X]  [A-X] ' | __2__ | grep --color
echo
exit $v