#!/usr/bin/tcsh
clear
if( "$3" == "-c" )	then
	echo "   a  b  c  d  e  f  g  h\n"
	grep -o ' [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_],' memboard | grep -n '.' | tr ':,' '  ' > tmp
	seq 10 10 50 >> tmp
	sort tmp | grep -C0  '[0-6]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_] ' | tr -d '-'
	echo "\n-------------------------\n"
endif
cat memboard | tr ',' '\n' | cat -n > file
grep -e '\<'$1'\>' -e '\<'$2'\>' file > tmp2
set v = `cat tmp2 | tr -cd '[A-X\n]' | uniq -c | tr -cd '0-9'` # v = 2 is true
grep -v -e '\<'$1'\>' -e '\<'$2'\>' file | tr '[A-X]' '?' >> tmp2
sort tmp2 | tr -cd 'A-X?_\n\t' | tr '\n\t' ', ' > tmp3
echo "   a  b  c  d  e  f  g  h\n"
grep -o ' [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_], [A-X?_],' tmp3 | grep -n '.' | tr ':,' '  ' > tmp4
seq 10 10 50 >> tmp4
sort tmp4 | grep -C0  '[0-6]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_]  [A-X?_] ' | tr -d '-' | grep --color -C1 '[A-X ]'
echo
exit $v