#!/usr/bin/tcsh
while 1
	while 1
		echo -n "\nEnter your choice: "
		set ch = $<:q
		echo $ch | grep -o '.' | grep -ni '[A-X]' | grep '1' >& /dev/null && \
		echo $ch | grep -o '.' | grep -n '[0-9]' | grep '2' >& /dev/null && break
		echo "Invalid choice. Please try again."
	end
	expr `echo $ch | grep -o '.' | sort | tr '\na-h' '+1-8' | grep -o '.' | tr '\n' ' ' | xargs echo "8 \*"` -8 > gettmp
	set t = `cat gettmp`
	if ( "$1" != "$t" ) cat memboard | tr ',' '\n' | grep -n '[A-X]' | grep '^'$t':' && exit $t
	echo "That place is already revealed. Please try again."
end
