#!/usr/bin/tcsh
echo ABCDEFGHIJKLMNOPQRSTUVWX | grep -no '.' | tr -d '0-9' | tee letters | tr 'A-X' 'a-x' >> letters
sort -R letters | tr 'a-x:\n' 'A-X ,' > memboard
set x = 0
set y = 0
set counter = 0
while 1
	./displayboard x y -c
if ( $? == 0 ) then
	cat memboard | tr `head -1` '_' > tmp
	cat tmp > memboard
	grep '[A-X]' && echo 'Congratulations! Finished in 26 moves.' && exit
endif
./getchoice 0

./displayboard __1__ 0 __3__